# Exercise Workflow
# Covers:
# - Workflow definition and naming
# - Multiple triggers (push, pull_request, workflow_dispatch)
# - Multiple jobs with dependencies and parallelism
# - Steps: shell commands and actions
# - Actions: uses community actions
# - Runners: specifies runner type
# - Matrix builds for Node.js versions
# - Job dependencies with 'needs'
# - Manual trigger support

name: 01 - Exercise Workflow # Workflow naming

on: # Workflow triggers
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs: # Jobs definition
  build: # Job: build
    runs-on: ubuntu-latest # Runner selection (hosted)
    steps: # Steps in job
      - name: Checkout code
        uses: actions/checkout@v4 # Action usage
      - name: Install dependencies
        run: npm ci # Shell command step
      - name: Run tests
        run: npm test # Shell command step

  lint: # Job: lint
    runs-on: ubuntu-latest
    needs: build # Job dependency
    steps:
      - name: Lint code
        run: npm run lint

  test-matrix: # Job: matrix build
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14, 16, 20] # Matrix strategy
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Action usage
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy: # Job: deploy
    runs-on: ubuntu-latest
    needs: [lint, test-matrix] # Multiple job dependencies
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy
        run: echo "Deploying to production"