name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types: [opened, synchronize]      # Activity types: only on PR opened or synchronized
    branches: [main]                  # Event filter: only if base branch is main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main."