name: 05 - 2 - Event Filters and Activity Types

on:
  pull_request:
    types: [closed]         # Activity type: only on PR closed
    branches: [main]        # Event filter: only if base branch is main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Running whenever a PR is closed."