name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        required: false
        default: false
        type: boolean
      target:
        description: "Which environment the workflow will target"
        required: true
        type: environment
      tag:
        description: "Release from which to build and deploy"
        required: false
        default: v3
        type: choice
        options:
          - v1
          - v2
          - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.dry-run == 'false' || inputs.dry-run == false }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"